# kubectl apply -f chap-7-fail-green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fail-green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/nonexistent-file

