#kubectl apply -f chap-8-db-user-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: configmap-secret-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: DB_USER # Notice that the case is different here
                        # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: db-config # The ConfigMap this value comes from.
              key: db_user # The key to fetch.
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: secrets
        mountPath: "/etc/secrets"
        readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: db-config
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "db_connection_string"
          path: "db_connection_string"
        - key: "DB_NAME"
          path: "db_name"
    - name: secrets
      secret:
        secretName: db-password
